# Site settings
title: CYD-poolen
email: admin@cyd.liu.se
description: > # this means to ignore newlines until "baseurl:"
  CYD-poolens datorsal vid Linköpings Universitet.
baseurl: "/cyd/_site" # the subpath of your site, e.g. /blog/
url: "http://rovanion.se" # the base hostname & protocol for your site
twitter_username: rovanion
github_username: rovanion

# Build settings
markdown: kramdown

kramdown:
auto_id: true